#---------------------------------------------
from src.scheme.object import object

import dearpygui.dearpygui as dpg


def set_visibility():
    visibility_info()
    visibility_lidar()
    visibility_capture()
    visibility_edge()
    visibility_node()
    visibility_cloud()
    visibility_control()
    visibility_link()

def visibility_lidar():
    dpg.hide_item(object.object.train.ID_icon_lidar_visibility)

    dpg.show_item(object.object.train.ID_l1_status)
    dpg.show_item(object.object.train.ID_l1_motor_visibility)
    dpg.show_item(object.object.train.ID_l1_stat_visibility)
    dpg.show_item(object.object.train.ID_l1_ip_visibility)
    dpg.show_item(object.object.train.ID_l1_motor_speed_visibility)
    dpg.show_item(object.object.train.ID_l1_sock_client_port_visibility)

    dpg.show_item(object.object.train.ID_l2_line_visibility)
    dpg.show_item(object.object.train.ID_l2_ip_visibility)
    dpg.show_item(object.object.train.ID_l2_motor_speed_visibility)
    dpg.show_item(object.object.train.ID_l2_sock_client_port_visibility)
    dpg.show_item(object.object.train.ID_l2_status)
    dpg.show_item(object.object.train.ID_l2_motor_visibility)
    dpg.show_item(object.object.train.ID_l2_stat_visibility)
def visibility_capture():
    dpg.show_item(object.object.capture.ID_thread_visibility)
    dpg.show_item(object.object.capture.ID_ip_visibility)
    dpg.show_item(object.object.capture.ID_sock_server_l1)
    dpg.show_item(object.object.capture.ID_sock_client_l1)
    dpg.show_item(object.object.capture.ID_sock_server_l2)
    dpg.show_item(object.object.capture.ID_sock_client_l2)
    dpg.show_item(object.object.capture.ID_sock_client_l2)
    dpg.show_item(object.object.capture.ID_device_visibility)
    dpg.show_item(object.object.capture.ID_sock_server_l1_port_visibility)
    dpg.show_item(object.object.capture.ID_sock_server_l2_port_visibility)
    dpg.show_item(object.object.capture.ID_sock_server_l2)
    dpg.show_item(object.object.capture.ID_http_server_port_visibility)
def visibility_edge():
    dpg.show_item(object.object.edge_1.ID_sock_client_l1_lidar_main)
    dpg.show_item(object.object.edge_1.ID_sock_client_l1_o)
    dpg.show_item(object.object.edge_1.ID_sock_server_l1_i)
    dpg.show_item(object.object.edge_1.ID_sock_client_l1_i)
    dpg.show_item(object.object.edge_1.ID_source_1)
    dpg.show_item(object.object.edge_1.ID_source_2)
    dpg.show_item(object.object.edge_1.ID_sock_client_l2_source)
    dpg.show_item(object.object.edge_1.ID_sock_client_l2_o)
    dpg.show_item(object.object.edge_1.ID_sock_server_l2_i)
    dpg.show_item(object.object.edge_1.ID_mqtt_visibility)
    dpg.show_item(object.object.edge_1.ID_ip_visibility)
    dpg.show_item(object.object.edge_1.ID_thread_visibility)
    dpg.show_item(object.object.edge_1.ID_http_server_port_visibility)
    dpg.show_item(object.object.edge_1.ID_http_server_o)
    dpg.show_item(object.object.edge_1.ID_http_client_o)
    dpg.show_item(object.object.edge_1.ID_sock_server_l1_port_visibility)
    dpg.show_item(object.object.edge_1.ID_sock_server_l2_port_visibility)
    dpg.show_item(object.object.edge_1.ID_sock_client_l2_o)
    dpg.show_item(object.object.edge_1.ID_sock_server_l2_i)

    dpg.show_item(object.object.edge_1.slam.ID_sock_server_port_visibility)
def visibility_cloud():
    dpg.show_item(object.object.operator.ID_mqtt_broker_port_visibility)
    dpg.show_item(object.object.operator.ID_mqtt_topic_visibility)
    dpg.show_item(object.object.operator.ID_ip_visibility)
def visibility_control():
    dpg.show_item(object.object.control.ID_temperature_visibility)
    dpg.show_item(object.object.control.ID_thread_visibility)
    dpg.show_item(object.object.control.ID_sock_server_l1_port_visibility)
    dpg.show_item(object.object.control.ID_sock_server_l2_port_visibility)
    dpg.show_item(object.object.control.ID_sock_server_l2)

    dpg.show_item(object.object.ssd.ID_parameter_visibility)
    dpg.show_item(object.object.ssd.ID_path_l1_visibility)
    dpg.show_item(object.object.ssd.ID_path_l2_visibility)
def visibility_info():
    dpg.configure_viewport("viewport", title="module_interface")
    dpg.hide_item("icon_computer_visible")
    dpg.show_item("l2_plot_visible")
    dpg.show_item("table_mongo")
    dpg.show_item("ID_nb_prediction_visibility")
    dpg.show_item("ID_nb_frame_visibility")
def visibility_node():
    dpg.hide_item("node_block_train")
    dpg.hide_item("node_block_edge")
    dpg.hide_item("node_block_cloud")
    dpg.show_item("node_slam")
    dpg.show_item("node_ai")
    dpg.show_item(object.object.edge_2.ID_node)
    dpg.show_item("node_ssd")
    dpg.show_item("node_cloud_car")
    dpg.show_item("node_control")
def visibility_link():
    dpg.show_item("link_l1_py")
    dpg.show_item("link_l2_py")
    dpg.show_item("link_edge_1_car_http")
    dpg.show_item("link_edge_1_ai_http")
    dpg.show_item("link_edge_1_interface_l1_sock")
    dpg.show_item("link_edge_1_interface_l2_sock")
    dpg.show_item("link_edge_1_processing_http")
    dpg.show_item("link_edge_1_processing_sock")
    dpg.show_item("link_capture_edge_1_l2_sock")
    dpg.show_item("link_edge_1_control_http")
    dpg.show_item("link_control_ssd_usb")
    dpg.show_item("link_capture_edge_1_l1_sock")
    dpg.show_item("link_capture_edge_1_l2_sock")
    dpg.show_item("link_edge_2_ai_http")
    dpg.show_item("link_edge_2_processing_http")
